FROM java
COPY spring-boot-hello-world/target/hello-world-0.0.1-SNAPSHOT.jar /opt/spring-boot-hello-world-server/hello-world-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/opt/spring-boot-hello-world-server/hello-world-0.0.1-SNAPSHOT.jar"]
